In [7]:
import pandas as pd

df = pd.read_excel(r"C:\Users\Access\Desktop\Meth_Pr\data\Sleep_Work_Productivity_Surve2026-04-24_13_03_21.xlsx")

# clean age column

df['Enter your age ?']= df['Enter your age ?'].fillna(df['Enter your age ?'].median())

# rename the columns

df.rename(columns={
    'How would you rate your overall work productivity?': 'work_productivity',
    'How much do you think your sleep affects your productivity at work?': 'sleep_productivity_effect',
    'What factors do you believe impact your sleep quality? (Select all that apply)': 'sleep_factors',
    'How many breaks do you take during your workday when you are tired ?': 'break_nums',
    'How would you describe your energy levels throughout the workday?': 'energy_levels_per_workday',
    'What is your primary work environment?': 'primary_work_environment',
    'what is you gender ?': 'gender',
    'On a typical work night, how many hours of sleep do you get?': 'sleep_hours',
    
    'I wake up feeling refreshed and ready for work.':
        'wake_up_refreshed',

    'I have difficulty falling asleep the night before an important workday.':
        'difficulty_falling_asleep',

    'Enter your age ?':
        'age',

    'I wake up multiple times during the night and struggle to go back to sleep.':
        'wake_up_multiple_times',

    'On weekends or days off, my sleep schedule is very different from my workday schedule (e.g., sleeping in more than 2 hours later).':
        'weekend_sleep_schedule_difference',

    'I use electronic devices (phone, laptop, TV) in bed within 30 minutes of trying to sleep.':
        'device_use_before_sleep',

    'I find it hard to concentrate on work tasks for more than 15–20 minutes at a time.':
        'difficulty_concentrating',

    'I make careless mistakes (e.g., typos, miscalculations, forgetting steps) that I would not have made if better rested.':
        'careless_mistakes',

    'I often have to re-read emails, documents, or instructions because I lost focus.':
        'reread_due_to_focus_loss',

    'Learning a new software, process, or skill at work feels unusually difficult for me.':
        'difficulty_learning_new_skills',

    'I struggle to generate new ideas or creative solutions to problems.':
        'difficulty_generating_ideas',

    'I forget important tasks, deadlines, or details from meetings.':
        'forget_tasks_deadlines',

    'I feel irritable or short-tempered with colleagues or clients.':
        'irritable_with_colleagues',

    'Small setbacks or minor criticism feel overwhelming or upsetting.':
        'small_setbacks_overwhelming',

    'I avoid collaboration or group work because I feel mentally exhausted.':
        'avoid_collaboration',

    'I have difficulty controlling my emotions during stressful work situations (e.g., tight deadlines, difficult customers).':
        'difficulty_controlling_emotions',

    'I feel physically tired, sluggish, or heavy-eyed during work, even without heavy physical exertion.':
        'physically_tired_at_work',

    'In my job, I have had a close call, minor accident, or injury that I attribute to being too tired. If your job is sedentary, answer based on accidents like tripping, bumping into things, or spilling hot liquids.':
        'accident_due_to_tiredness',

    'Compared to when I am well-rested, I estimate my current work output is...':
        'current_work_output',

    'In the past month, how many work days did you feel you were “present but not productive” (getting less than half of your normal output) due to poor sleep?':
        'unproductive_workdays_due_to_sleep'

}, inplace=True)



df = df.replace(r'\n', ', ', regex=True)
df["sleep_factors"] = df["sleep_factors"].str.split(", ")

In [5]:
df.head()

,Submission Date,work_productivity,sleep_productivity_effect,sleep_factors,break_nums,energy_levels_per_workday,primary_work_environment,gender,sleep_hours,wake_up_refreshed,...,difficulty_generating_ideas,forget_tasks_deadlines,irritable_with_colleagues,small_setbacks_overwhelming,avoid_collaboration,difficulty_controlling_emotions,physically_tired_at_work,accident_due_to_tiredness,current_work_output,unproductive_workdays_due_to_sleep
0,"Apr 24, 2026",High,Moderately,"Stress, Screen time before bed",3-4,High,Hybrid,Male,5–6 hrs,2,...,2,3,4,3,4,3,3,1,20–40% less,10
1,"Apr 24, 2026",Moderate,Moderately,Screen time before bed,3-4,Moderate,Hybrid,Female,6–7 hrs,3,...,3,3,3,3,3,3,3,3,60–80% less,13
2,"Apr 24, 2026",Very high,Extremely,"Stress, Exercise",1-2,High,Office,Female,More than 8 hrs,5,...,4,4,2,2,2,1,3,2,60–80% less,7
3,"Apr 24, 2026",High,Extremely,"Stress, Screen time before bed",3-4,Moderate,Hybrid,Female,6–7 hrs,2,...,4,2,2,2,2,2,3,3,20–40% less,20
4,"Apr 24, 2026",Moderate,Extremely,"Stress, Exercise, Screen time before bed, Room...",1-2,Moderate,Remote,Male,7–8 hrs,3,...,2,1,1,3,4,2,3,3,80–100% less,23

In [24]:
df['sleep_quality_and_hygiene_index_(SQLI)']=(df['wake_up_refreshed']+df['difficulty_falling_asleep']+df['wake_up_multiple_times']+df['weekend_sleep_schedule_difference']+df['device_use_before_sleep'])*100/25
df['Cognitive_at_task_perforamnce_index_(CTPI)']=(((df['difficulty_concentrating']+df['careless_mistakes']+df['reread_due_to_focus_loss']+df['difficulty_learning_new_skills']+df['difficulty_generating_ideas']+df['forget_tasks_deadlines'])*100/30).round(2))
df['Emotional_and_social_impact_index(ESII)']=((df['irritable_with_colleagues']+df['small_setbacks_overwhelming']+df['avoid_collaboration']+df['difficulty_controlling_emotions'])*100/20)
df['Physical_and_safety_risk_index(PSRI)']=((df['physically_tired_at_work']+df['accident_due_to_tiredness'])*100/10)
df['Presentative_index(PI)']=(((df['unproductive_workdays_due_to_sleep'])*100/50).round(2))
df['Overall_sleep_Productivity_Impact_index(SPI)']=((df['Cognitive_at_task_perforamnce_index_(CTPI)']+df['Emotional_and_social_impact_index(ESII)']+df['Physical_and_safety_risk_index(PSRI)']+df['Presentative_index(PI)'])*0.2927)

In [25]:
# data validation

df.describe()

,wake_up_refreshed,difficulty_falling_asleep,age,wake_up_multiple_times,weekend_sleep_schedule_difference,device_use_before_sleep,difficulty_concentrating,careless_mistakes,reread_due_to_focus_loss,difficulty_learning_new_skills,...,difficulty_controlling_emotions,physically_tired_at_work,accident_due_to_tiredness,unproductive_workdays_due_to_sleep,sleep_quality_and_hygiene_index_(SQLI),Cognitive_at_task_perforamnce_index_(CTPI),Emotional_and_social_impact_index(ESII),Physical_and_safety_risk_index(PSRI),Presentative_index(PI),Overall_sleep_Productivity_Impact_index(SPI)
count,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,...,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000
mean,2.921260,3.700787,24.303150,2.661417,3.700787,4.062992,2.677165,3.259843,3.377953,2.692913,...,2.929134,3.181102,2.464567,10.330709,68.188976,56.587874,57.480315,56.456693,20.661417,55.960230
std,0.956235,1.129088,10.050499,1.292349,1.236450,1.219862,1.174341,1.169809,1.119305,1.224821,...,1.169596,1.115670,1.132460,7.982178,11.752563,15.971627,16.569646,18.193299,15.964355,14.292164
min,1.000000,1.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,36.000000,20.000000,20.000000,20.000000,0.000000,25.368309
25%,2.000000,3.000000,19.000000,2.000000,3.000000,3.000000,2.000000,2.000000,3.000000,2.000000,...,2.000000,2.000000,2.000000,4.500000,60.000000,46.670000,45.000000,45.000000,9.000000,45.075800
50%,3.000000,4.000000,20.000000,3.000000,4.000000,5.000000,3.000000,3.000000,3.000000,2.000000,...,3.000000,3.000000,2.000000,10.000000,68.000000,56.670000,55.000000,60.000000,20.000000,55.905700
75%,4.000000,5.000000,21.500000,4.000000,5.000000,5.000000,3.000000,4.000000,4.000000,3.500000,...,4.000000,4.000000,3.000000,15.000000,76.000000,66.670000,70.000000,70.000000,30.000000,65.564800
max,5.000000,5.000000,54.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,50.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.006809